# Generated by Django 5.0.6 on 2024-07-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('topic', 'Topic'), ('podcast', 'Podcast'), ('tutor', 'Tutor')], max_length=20)),
                ('template', models.TextField()),
            ],
        ),
    ]
